---
title: "p8105_hw6_fl2714"
author: "Fangchi"
date: "2024-11-26"
output: github_document
---

```{r}

library(tidyverse)
library(modelr)
library(mgcv)
library(dplyr)
library(ggplot2)
library(purrr)
library(tidyr)
library(rsample)

```

### Problem 2

```{r}

# load data
url <- "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
homicide_data <- read.csv(url, stringsAsFactors = FALSE)

```


```{r}

cleaned_data <- homicide_data %>%
  mutate(city_state = paste(city, state, sep = ", ")) %>% # create variable
  mutate(solved_binary = ifelse(disposition == "Closed by arrest", 1, 0)) %>% # whether the homicide is solved
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")) %>%
  filter(victim_race %in% c("White", "Black")) %>% #  limit victim_race
  mutate(
    victim_age = ifelse(victim_age == "Unknown", NA, victim_age),  
    victim_age = as.numeric(victim_age)                            
  ) %>%
  drop_na(victim_age)  

```


```{r}

baltimore_data <- cleaned_data %>%
  filter(city_state == "Baltimore, MD")

glm_baltimore <- glm(solved_binary ~ victim_age + victim_sex + victim_race,
                     data = baltimore_data, family = "binomial")

baltimore_results <- broom::tidy(glm_baltimore, exponentiate = TRUE, conf.int = TRUE)
baltimore_results %>%
  filter(term == "victim_sexMale")

```


```{r}

city_results <- cleaned_data %>%
  group_by(city_state) %>%
  nest() %>%  
  mutate(
    glm_fit = map(data, ~ glm(solved_binary ~ victim_age + victim_sex + victim_race,
                              data = ., family = "binomial")),
    tidy_results = map(glm_fit, ~ broom::tidy(.x, exponentiate = TRUE, conf.int = TRUE))
  ) %>%
  unnest(tidy_results) %>%  
  filter(term == "victim_sexMale") %>% 
  select(city_state, estimate, conf.low, conf.high)

```
```{r}


city_results <- city_results %>%
  arrange(estimate) %>%
  mutate(city_state = factor(city_state, levels = city_state))  

ggplot(city_results, aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +
  labs(title = "Adjusted Odds Ratios (OR) by City",
       x = "City", y = "OR (Male vs Female Victims)") +
  theme_minimal()

```

### Problem 3

```{r}

birthweight <- read.csv("data/birthweight.csv")

```


```{r}

birthweight <- birthweight %>%
  mutate(
    babysex = factor(babysex, levels = c(1, 2), labels = c("Male", "Female")),
    malform = factor(malform, levels = c(0, 1), labels = c("Absent", "Present")),
    frace = factor(frace),
    mrace = factor(mrace)
  ) %>%
  drop_na()  

```


```{r}


model_hypothesis <- lm(bwt ~ babysex + bhead + blength + gaweeks + wtgain + smoken, data = birthweight)


summary(model_hypothesis)


```

```{r}


birthweight <- birthweight %>%
  add_predictions(model_hypothesis, var = "pred") %>%
  add_residuals(model_hypothesis, var = "resid")

ggplot(birthweight, aes(x = pred, y = resid)) +
  geom_point(alpha = 0.5) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(title = "Residuals vs Fitted Values",
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()

```
```{r}

model_main_effects <- lm(bwt ~ blength + gaweeks, data = birthweight)
summary(model_main_effects)

```
```{r}

model_interactions <- lm(bwt ~ bhead * blength * babysex, data = birthweight)
summary(model_interactions)

```
```{r}

set.seed(123)  
cv_df <- crossv_mc(birthweight, 100) %>%  
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )

cv_df <- cv_df %>%
  mutate(
    model_hypothesis = map(train, ~ lm(bwt ~ babysex + bhead + blength + gaweeks + wtgain + smoken, data = .)),
    model_main_effects = map(train, ~ lm(bwt ~ blength + gaweeks, data = .)),
    model_interactions = map(train, ~ lm(bwt ~ bhead * blength * babysex, data = .)),
    rmse_hypothesis = map2_dbl(model_hypothesis, test, ~ rmse(model = .x, data = .y)),
    rmse_main_effects = map2_dbl(model_main_effects, test, ~ rmse(model = .x, data = .y)),
    rmse_interactions = map2_dbl(model_interactions, test, ~ rmse(model = .x, data = .y))
  )

```


```{r}

cv_long <- cv_df %>%
  select(starts_with("rmse")) %>%
  pivot_longer(
    cols = everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  )


ggplot(cv_long, aes(x = model, y = rmse)) +
  geom_violin() +
  labs(title = "Cross-Validated RMSE for Each Model",
       x = "Model",
       y = "RMSE") +
  theme_minimal()

```

